Repository itzg/docker-minecraft-server, pull requests merged in 2022-12, with the labels that each got.

#1854 Bump mc-image-helper to 1.22.11
  Dockerfile
Labels: dependencies

#1860 Clarify whitelist variables (enable vs enforce)
  README.md
Labels: documentation

#1870 Allow DEBUG env var to enable mc-image-helper debug logs
  Dockerfile
Labels: enhancement

#1873 Fixed format as code for MOTD newline escape
  README.md
Labels: documentation

#1875 Noted about not using quotes in environment list syntax
  README.md
Labels: documentation

#1879 Added FORCE_REDOWNLOAD support for Bukkit/Spigot
  README.md
  scripts/start-deployBukkitSpigot
Labels: enhancement
