Repository itzg/docker-minecraft-server, pull requests merged in 2022-10, with the labels that each got.

#1769 Auto-manage server properties by default
  .github/release.yml
  README.md
  scripts/start-setupServerProperties
Labels: enhancement

#1773 Prevent generic modpack overwriting eula file
  scripts/start-setupModpack
Labels: enhancement

#1779 Setup MEMORY variables earlier to allow use in Spigot build
  scripts/start-configuration
  scripts/start-finalExec
Labels: enhancement

#1780 Only default MOTD and WHITELIST when first creating server.properties
  scripts/start-configuration
  scripts/start-setupServerProperties
Labels: bug

#1787 Emphasize java 8 requirement for Forge < 1.18
  README.md
Labels: documentation

#1788 Improved naming of FORGE_FORCE_REINSTALL and FORGE_VERSION
  README.md
  examples/docker-compose-forge-bettermcplus
  examples/docker-compose-generic-pack-tnp5.yml
  examples/docker-compose-generic-pack.yml
  examples/docker-compose-rlcraft.yml
  examples/docker-compose-spongeforge.yml
  scripts/start-deployForge
Labels: documentation

#1798 Added support for datapack enable/disable properties for feature flags
  README.md
  scripts/start-setupServerProperties
Labels: enhancement

#1799 Added example of INITIAL_ENABLED_PACKS
  README.md
Labels: documentation

#1800 Added kustomize base files
  kustomize/README.md
  kustomize/base/kustomization.yml
  kustomize/base/service.yml
  kustomize/base/statefulset.yml
Labels: enhancement

#1808 Remove duplicate VIEW_DISTANCE env variable
  examples/docker-compose-curseforge-atm7.yaml
Labels: documentation

#1811 Document command to find host path of anonymous volume
  README.md
Labels: documentation
