Repository itzg/docker-minecraft-server, pull requests merged in 2023-04, with the labels that each got.

#2057 Downloads handle content disposition filename with RFC 2047 encoding
  Dockerfile
Labels: bug

#2058 Redacts sensitive headers from debugs like with AUTO_CURSEFORGE
  Dockerfile
Labels: bug

#2059 With AUTO_CURSEFORGE handle modpacks not allowed for distribution by author
  Dockerfile
  README.md
  examples/one-block-modded/.gitignore
  examples/one-block-modded/docker-compose.yml
Labels: enhancement

#2063 Tweak level of new docs link
  README.md
Labels: documentation

#2071 By default, generate random RCON password at startup
  Dockerfile
  README.md
  scripts/start
  scripts/start-configuration
  tests/setuponlytests/defaults/verify.sh
Labels: enhancement

#2072 autocf: use VERSION resolved from modpack
  Dockerfile
  scripts/start-deployAutoCF
Labels: bug

#2051 possible solution to deploy to both dockerhub and ghcr
  .github/workflows/build-multiarch.yml
Labels: ci/push-image

#2093 Probably quote content passed to mc-send-to-console
  bin/mc-send-to-console
Labels: bug

#2094 modrinth: ensure non-required dependency doesn't mask explicit project request
  Dockerfile
Labels: bug

#2095 autocf: remove usage of old parallel downloads option
  .github/workflows/verify-pr.yml
  scripts/start-deployAutoCF
Labels: bug

#2105 Add JSON5 support for patch files
  Dockerfile
Labels: enhancement

#2106 autocf: add support for specifying a downloads repo
  Dockerfile
  README.md
  docs/example-autocf-downloads.drawio.png
  examples/atm8/docker-compose.yml
  scripts/start-deployAutoCF
Labels: enhancement

#2110 docs: added filebrowser sidecar example
  examples/atm8/docker-compose.yml
  examples/atm8/filebrowser.json
Labels: documentation
