Repository itzg/docker-minecraft-server, pull requests merged in 2023-03, with the labels that each got.

#1987 modrinth: adapt version lookup to API changes
  Dockerfile
  scripts/start-setupModpack
Labels: bug

#1989 Revert "modrinth: adapt version lookup to API changes (#1987)"
  Dockerfile
  scripts/start-setupModpack
Labels: bug

#1990 Ensure Modrinth support specifies paper/purpur loader as needed
  Dockerfile
  scripts/start-setupModpack
Labels: bug

#1991 Fix Modrinth download when no version files are primary
  Dockerfile
Labels: bug

#1992 Unzip Modrinth files that are zips
  Dockerfile
Labels: enhancement

#2004 Clarify in docs to not port forward RCON unless secure
  Dockerfile
  README.md
Labels: documentation

#2005 Verify java compatibility for AUTO_CURSEFORGE
  scripts/start-configuration
Labels: bug

#2006 Allow for latest Forge version to be behind vanilla version
  Dockerfile
  scripts/start-deployForge
Labels: bug

#2012 Extract versions from provided Forge installer
  Dockerfile
Labels: bug

#2015 autocf: improve error message when modpack file is missing manifest
  Dockerfile
Labels: enhancement

#2016 Fixing Modrinth projects support for non-Forge
  scripts/start-setupModpack
Labels: bug

#2018 autocf: adjusted excludes for valhesia-5
  examples/valhesia5/docker-compose.yml
  files/cf-exclude-include.json
Labels: documentation

#2019 autocf: allow for exclude/include file and list
  Dockerfile
  README.md
  scripts/start-deployAutoCF
Labels: enhancement

#2024 autocf: fixed issue where exclude file alone was ignored
  Dockerfile
Labels: bug

#2032 forge: support version discovery of 1.5, 1.7 installer
  Dockerfile
Labels: bug

#2040 autocf: ensure modpack query is not cached too much
  Dockerfile
Labels: bug

#2043 autocf: switch to official CurseForge API, but needs CF_API_KEY
  Dockerfile
  README.md
  examples/atm8/docker-compose.yml
  examples/one-block-modded/docker-compose.yml
  examples/pixelmon/docker-compose.yml
  examples/valhesia5/docker-compose.yml
  examples/vault-hunters-1-18-2/docker-compose.yml
  tests/setuponlytests/auto_curseforge/docker-compose.yml
  tests/setuponlytests/auto_curseforge/require.sh
Labels: enhancement

#2046 autocf: determine mod file availability from downloadUrl
  Dockerfile
Labels: bug

#2050 added information on the escaping of $ in the CF API Key
  README.md
Labels: documentation

#2054 added docs to use env file
  README.md
Labels: documentation
