Repository itzg/docker-minecraft-server, pull requests merged in 2023-06, with the labels that each got.

#2197 Improved handling of MODS and PLUGINS lists using mcopy
  Dockerfile
  docs/mods-and-plugins/index.md
  examples/geyser/docker-compose.yml
  scripts/start-deployPaper
  scripts/start-setupModpack
  scripts/start-utils
Labels: enhancement

#2198 Fixed example Geyser compose file
  examples/geyser/docker-compose.yml
Labels: documentation

#2199 Corrected broken links in types and mods
  docs/mods-and-plugins/index.md
  docs/types-and-platforms/mod-platforms/auto-curseforge.md
  docs/types-and-platforms/mod-platforms/ftb.md
  docs/types-and-platforms/mod-platforms/modrinth-modpacks.md
  docs/types-and-platforms/server-types/bukkit-spigot.md
  docs/types-and-platforms/server-types/fabric.md
  docs/types-and-platforms/server-types/forge.md
  docs/types-and-platforms/server-types/others.md
  docs/types-and-platforms/server-types/paper.md
  docs/types-and-platforms/server-types/quilt.md
  docs/versions/java.md
Labels: documentation

#2200 For backward compatibility, allow MODS to list plugins for those server types
  docs/mods-and-plugins/index.md
  kustomize/base/kustomization.yml
  scripts/start-setupModpack
  scripts/start-setupMounts
Labels: enhancement, documentation

#2205 Add ENFORCE_SECURE_PROFILE to docs table
  docs/configuration/server-properties.md
Labels: documentation

#2206 Sort "other server property mappings"
  docs/configuration/server-properties.md
Labels: documentation

#2210 docs: fixed building page formatting and added base image info
  docs/misc/contributing/building.md
Labels: documentation

#2211 Switch to mc-image-helper for installing Paper/Folia
  Dockerfile
  scripts/start-deployFolia
  scripts/start-deployPaper
Labels: bug

#2212 docs: updated development notes to use jwebserver
  docs/misc/contributing/development.md
Labels: documentation

#2215 Use mc-image-helper for Purpur
  Dockerfile
  scripts/start-deployPurpur
Labels: enhancement

#2223 docs: add docker compose usage to intro
  docs/index.md
Labels: documentation

#2229 Switch Quilt and Purpur to image helper
  Dockerfile
  docs/misc/contributing/development.md
  examples/atm8/docker-compose.yml
  examples/modrinth-modpack/docker-compose.yml
  examples/modrinth-paper/docker-compose.yml
  examples/one-block-modded/docker-compose.yml
  examples/pixelmon/docker-compose.yml
  examples/valhesia5/docker-compose.yml
  examples/vault-hunters-1-18-2/docker-compose.yml
  notes/Going from docker run to compose.drawio.png
  notes/start-script-flow.drawio.png
  scripts/start-configuration
  scripts/start-deployAutoCF
  scripts/start-deployBukkitSpigot
  scripts/start-deployCrucible
  scripts/start-deployFabric
  scripts/start-deployForge
  scripts/start-deployMagma
  scripts/start-deployModrinth
  scripts/start-deployMohist
  scripts/start-deployPufferfish
  scripts/start-deployQuilt
  scripts/start-deploySpongeVanilla
  scripts/start-deployVanilla
  scripts/start-setupForgeApiMods
  scripts/start-setupModpack
  scripts/start-utils
  tests/setuponlytests/auto_curseforge/docker-compose.yml
  tests/setuponlytests/modrinth/docker-compose.yml
  tests/setuponlytests/modrinth/fake.jar
Labels: enhancement

#2235 Ensure VERSION is resolved from existing Fabric install
  Dockerfile
  docs/index.md
  docs/misc/deployment/aws.md
  docs/misc/deployment/docker-compose.md
  docs/misc/deployment/helmcharts.md
  docs/misc/deployment/index.md
Labels: bug, documentation

#2237 Reconcile VERSION for TYPE=CURSEFORGE
  scripts/start-deployCF
Labels: bug

#2240 auto_cf: allow explicit inclusions to override default exclusions
  Dockerfile
  files/cf-exclude-include.json
Labels: enhancement

#2241 docs: tighten up wording in auto-pause section
  docs/misc/autopause-autostop/autopause.md
  docs/misc/autopause-autostop/autostop.md
Labels: documentation

#2243 modrinth: reduce API pressure with initial bulk get of projects
  Dockerfile
Labels: enhancement

#2248 Provide `stable` image tag that tracks latest repo tag
  .github/workflows/build-multiarch.yml
Labels: enhancement

#2253 Added CUSTOM_JAR_EXEC
  docs/types-and-platforms/server-types/others.md
  scripts/start-deployCustom
  scripts/start-finalExec
Labels: enhancement, documentation

#2258 Update rcon-cli to remove config file loading message
  Dockerfile
Labels: enhancement

#2259 Typo :)
  docs/types-and-platforms/mod-platforms/auto-curseforge.md
Labels: documentation

#2260 docs: adjusted wording of CF_MODPACK_ZIP option
  docs/types-and-platforms/mod-platforms/auto-curseforge.md
Labels: documentation
