Repository itzg/docker-minecraft-server, pull requests merged in 2023-07, with the labels that each got.

#2262 Ensure datapacks cleanup doesn't remove vanillatweaks
  notes/.gitignore
  notes/start-script-flow.drawio.png
  scripts/start-setupDatapack
  scripts/start-setupVanillaTweaks
  scripts/start-setupWorld
Labels: bug

#2263 auto_cf: write mods needing manual download to file
  Dockerfile
  docs/types-and-platforms/mod-platforms/auto-curseforge.md
  examples/.gitignore
  examples/rlcraft/docker-compose.yml
Labels: enhancement

#2266 examples: simplified filebrowser example
  examples/atm8/docker-compose.yml
Labels: documentation

#2267 Remove .mc-health.env when not needed
  scripts/start-finalExec
Labels: bug

#2271 Update cf-exclude-include.json
  files/cf-exclude-include.json
Labels: enhancement

#2274 Corrected VERSION resolution with FTBA mod platform/type
  scripts/start-deployFTBA
Labels: bug

#2277 Use CXF compatible with Java 8
  Dockerfile
Labels: bug

#2278 Allow REPLACE_ENV_VARIABLE_PREFIX to be an empty string
  docs/configuration/interpolating.md
  scripts/start-setupMounts
Labels: enhancement

#2279 docs: added Better MC example
  examples/atm8/docker-compose.yml
  examples/bettermc/docker-compose.yml
  examples/downloads/.gitignore
Labels: documentation

#2285 Allow blank REPLACE_ENV_VARIABLE_PREFIX when processing in-place files
  scripts/start-setupEnvVariables
Labels: bug

#2286 auto-cf: stop startup with info when manual mod downloads are needed
  Dockerfile
Labels: enhancement

#2288 auto-cf: clarify why some mods need to be manually downloaded
  Dockerfile
Labels: enhancement

#2292 Include SPIGET_RESOURCES support for hybrid server types
  notes/start-script-flow.drawio.png
  scripts/start-deployCatserver
  scripts/start-deployCrucible
  scripts/start-deployMagma
  scripts/start-deployMohist
Labels: bug

#2301 docs: corrected Java 20 typo
  docs/versions/java.md
Labels: documentation

#2305 ftb: added FTB_FORCE_REINSTALL
  docs/types-and-platforms/mod-platforms/ftb.md
  scripts/start-deployFTBA
Labels: enhancement

#2308 auto-cf: updated API parsing for NeoForge mod loader type
  Dockerfile
Labels: bug, enhancement
