Repository itzg/docker-minecraft-server, pull requests merged in 2024-12, with the labels that each got.

#3174 Switch FTBA to use https://api.feed-the-beast.com/v1
  examples/ftba/compose.yml
  scripts/start-deployFTBA
Labels: enhancement

#3176 Fixed new FTB installer args and manifest
  scripts/start-deployFTBA
Labels: bug

#3177 Re-install FTB if manifest is missing
  scripts/start-deployFTBA
Labels: bug

#3181 Added xaeroplus and yungs-menu-tweaks to the exclude list
  files/cf-exclude-include.json
Labels: enhancement, type/curseforge

#3186 Make sure download new version of FTB installer
  scripts/start-deployFTBA
Labels: bug

#3188 Corrected examples link in autopause docs
  docs/misc/autopause-autostop/autopause.md
Labels: documentation

#3196 docs: clarified Modrinth support includes plugins and datapacks
  docs/mods-and-plugins/modrinth.md
Labels: documentation

#3197 Clarify Modrinth URL structure in documentation
  docs/mods-and-plugins/modrinth.md
Labels: documentation

#3198 Add example of Craftoria modpack
  examples/craftoria/docker-compose.yml
Labels: documentation

#3205 docs: clarify curseforge listing file and GetBukkit limitation
  docs/Dockerfile
  docs/mods-and-plugins/curseforge-files.md
  docs/types-and-platforms/server-types/bukkit-spigot.md
Labels: documentation

#3213 fix vault hunters example
  examples/vault-hunters-1-18-2/docker-compose.yml
Labels: documentation

#3215 Cache CF search API calls and better handle CURSEFORGE_FILES rate limit
  Dockerfile
Labels: enhancement

#3216 Download default spigot.yml for PaperMC to top-level directory
  scripts/start-deployPaper
  scripts/start-setupEnvVariables
  scripts/start-utils
Labels: bug
