Repository itzg/docker-minecraft-server, pull requests merged in 2024-07, with the labels that each got.

#2938 docs: updating AUTO_CURSEFORGE examples that no longer need /downloads
  examples/aof7/docker-compose.yml
  examples/atm8/docker-compose.yml
  examples/atm9/docker-compose.yml
  examples/auto-cf/using-excludes/docker-compose.yml
  examples/bettermc/docker-compose.yml
  examples/rad2/compose.yaml
  examples/vault-hunters-1-18-2/docker-compose.yml
  files/cf-exclude-include.json
Labels: documentation

#2939 add check for absolute directories to world copy script
  scripts/start-setupWorld
Labels: bug

#2943 cf: add support for modpacks that use NeoForge
  Dockerfile
Labels: enhancement

#2948 Add ryoamiclights to CF global excludes
  files/cf-exclude-include.json
Labels: enhancement

#2966 Clarify MODRINTH_ALLOWED_VERSION_TYPE inclusion
  docs/mods-and-plugins/modrinth.md
Labels: documentation

#2970 Fixed exclusion of no-night-vision-flashing
  files/cf-exclude-include.json
  scripts/start-deployAutoCF
Labels: bug

#2982 modrinth: add default exclusions discovered for prominence 2
  files/modrinth-exclude-include.json
Labels: enhancement

#2985 cf: check downloads repo before attempting download of mod in modpack
  Dockerfile
Labels: enhancement

#2986 cf: copy files found in downloads repo
  Dockerfile
Labels: bug

#2989 mcopy: support basic auth via URL
  Dockerfile
Labels: enhancement

#2991 auto-cf: remove necronomicon from global exclusions
  files/cf-exclude-include.json
Labels: bug

#2993 Avoid logging userinfo from MODS/PLUGINS URLs
  Dockerfile
Labels: bug

#2999 Re-download Modrinth projects based on modified time rather than filename existence
  Dockerfile
Labels: bug

#3000 paper: suggest other release channel when build not found
  Dockerfile
  docs/types-and-platforms/server-types/paper.md
Labels: enhancement, documentation

#3003 auto-cf: added blur-forge to global excludes
  files/cf-exclude-include.json
Labels: enhancement

#3004 paper: download default configs before patching
  scripts/start-deployPaper
  scripts/start-finalExec
  scripts/start-setupEnvVariables
  scripts/start-utils
Labels: enhancement

#3006 Updated and Improved install scripts.
  build/alpine/install-packages.sh
  build/ol/install-gosu.sh
  build/ol/install-packages.sh
  build/ubuntu/install-packages.sh
Labels: enhancement

#3014 Add itemphysic-lite to global exclude
  files/cf-exclude-include.json
Labels: enhancement

#3020 docs: add service annotation patching to example kustomization
  .github/workflows/build-multiarch.yml
  .github/workflows/verify-pr.yml
  kustomize/README.md
Labels: documentation

#3017 docs: updated with example on how to setup lazymc with minecraft container
  docs/misc/examples.md
  examples/lazymc/docker_compose.yml
Labels: documentation
