Repository itzg/docker-minecraft-server, pull requests merged in 2024-11, with the labels that each got.

#3135 add ftb-evolution example file
  examples/ftb-evolution/compose.yaml
Labels: documentation

#3139 Correctly handle NeoForge CF modpacks also using CURSEFORGE_FILES
  scripts/start-setupModpack
Labels: bug

#3143 Create ATM10 example
  examples/atm10/docker-compose.yml
Labels: documentation

#3142 modrinth: more info in error when dependency has no applicable files
  Dockerfile
  tests/setuponlytests/vanillatweaks_file/docker-compose.yml
  tests/setuponlytests/vanillatweaks_file/require.sh
Labels: enhancement

#3149 deps: upgrade mc-monitor to 0.15.0
  Dockerfile
Labels: dependencies

#3156 Include processing of SPIGET_RESOURCES with TYPE=CUSTOM
  scripts/start-deployCustom
Labels: enhancement

#3164 cf: added default excludes needed for ATM10
  examples/atm10/docker-compose.yml
  examples/autopause/compose.yml
  files/cf-exclude-include.json
Labels: enhancement

#3166 docs: adjust memory and volume in atm10 example
  examples/atm10/docker-compose.yml
Labels: documentation

#3167 Correcting name of .mc-health.env file
  scripts/start-finalExec
Labels: bug

#3158 cf: use fallback URL for curseforge files like modpack files
  Dockerfile
Labels: enhancement
