Repository itzg/docker-minecraft-server, pull requests merged in 2024-06, with the labels that each got.

#2867 Enhance CurseForge server packs that use variables.txt
  scripts/start-finalExec
Labels: enhancement

#2869 docs: allow for toggling light/dark mode
  mkdocs.yml
Labels: documentation

#2873 docs: fixed description of BROADCAST_RCON_TO_OPS variable
  docs/variables.md
Labels: documentation

#2881 Added note about CurseForge files dependency handling
  docs/mods-and-plugins/curseforge-files.md
Labels: documentation

#2883 paper: download default configs to allow for patching
  scripts/start-deployPaper
Labels: enhancement

#2884 cf: verify mod file hashes and re-download to repair
  Dockerfile
Labels: enhancement

#2885 build: upgrade tools to Go 1.22.4
  Dockerfile
Labels: dependencies

#2891 Fixed issue of unbound REMOVE_OLD_MODS_EXCLUDE variable when using SPIGET_RESOURCES
  examples/spiget/docker-compose.yml
  scripts/start-spiget
  scripts/start-utils
Labels: bug

#2895 Disable default configs download until issues resolved
  scripts/start-deployPaper
Labels: bug

#2896 Fixed typo in CF files dependencies section title
  docs/mods-and-plugins/curseforge-files.md
Labels: documentation

#2898 Don't log RCON password when DEBUG enabled
  scripts/start-configuration
Labels: bug

#2902 paper: consider release channel when selecting version/build
  Dockerfile
  docs/types-and-platforms/server-types/paper.md
  scripts/start-deployPaper
Labels: enhancement

#2903 Added hairpin routing diagram
  notes/Hairpin routing.drawio.png
Labels: documentation

#2906 Add a section about class file version 65.0 message
  docs/versions/java.md
Labels: documentation

#2917 docs: updated to new name of itzg/mc-proxy
  docs/misc/related-projects.md
  examples/docker-compose-autopause.yml
  examples/multi-project/servers/docker-compose.yml
Labels: documentation

#2932 Update cf-exclude-include.json with Apple Skin, etc
  files/cf-exclude-include.json
Labels: enhancement

#2935 neoforge: correctly handle versioning that drops the ".0"
  Dockerfile
Labels: bug

#2937 modrinth: add support for default excludes/includes
  Dockerfile
  docs/types-and-platforms/mod-platforms/modrinth-modpacks.md
  examples/bmc4/docker-compose.yml
  examples/prominence2/docker-compose.yml
  files/modrinth-exclude-include.json
  scripts/start-deployModrinth
Labels: enhancement
