Repository itzg/docker-minecraft-server, pull requests merged in 2024-05, with the labels that each got.

#2814 docs: added more detail about autopauase rootless usage
  docs/misc/autopause-autostop/autopause.md
Labels: documentation

#2822 examples: updated bmc4 example
  examples/bmc4/docker-compose.yml
  examples/docker-compose-mods-mount.yml
Labels: documentation

#2826 docs: add info about DUMP_SERVER_PROPERTIES
  docs/configuration/server-properties.md
Labels: documentation

#2827 docs: add compose example of multiline MOTD
  docs/configuration/server-properties.md
  examples/multiline-motd/docker-compose.yml
Labels: documentation

#2831 build: upgrade rcon-cli and easy-add
  Dockerfile
Labels: dependencies

#2835 build: upgrading git-lfs from packagecloud
  Dockerfile
  build/alpine/install-packages.sh
  build/ol/install-packages.sh
  build/ubuntu/install-packages.sh
Labels: dependencies

#2839 Fixed internal SPIGOT family mapping
  scripts/start-utils
Labels: bug

#2846 Added a missing quotation mark
  docs/mods-and-plugins/index.md
Labels: documentation

#2848 cf: allow for trailing slash on CF modpack page URL
  Dockerfile
Labels: bug

#2850 build: upgrading git-lfs from packagecloud
  build/ol/install-packages.sh
  build/ubuntu/install-packages.sh
Labels: dependencies

#2852 Remove normalizing to uppercase of LEVEL_TYPE
  scripts/start-setupServerProperties
Labels: bug
