Repository itzg/docker-minecraft-server, pull requests merged in 2024-08, with the labels that each got.

#3027 Ketting removed GithubPackages
  docs/types-and-platforms/server-types/hybrids.md
Labels: documentation

#3029 Added support for FOLIA_CHANNEL
  docs/types-and-platforms/server-types/paper.md
  scripts/start-deployFolia
Labels: enhancement

#3028 Added client mod exclusions for modpack "Hardrock Terrafirmacraft"
  files/cf-exclude-include.json
Labels: enhancement

#3032 Add just-zoom (jar: justzoom) to global exclude
  files/cf-exclude-include.json
  files/modrinth-exclude-include.json
Labels: enhancement

#3037 docs: remove leftover debugs in bmc4 example
  examples/bmc4/docker-compose.yml
Labels: documentation

#3038 Default EXISTING_OPS_FILE and EXISTING_WHITELIST_FILE to MERGE
  docs/configuration/server-properties.md
  scripts/start-setupRbac
Labels: enhancement

#3042 Default EXISTING_OPS_FILE and EXISTING_WHITELIST_FILE to SYNC_FILE_MERGE_LIST
  docs/configuration/server-properties.md
  scripts/start-setupRbac
Labels: bug

#3044 cf-files: improve the logging of missing dependencies especially optional ones
  Dockerfile
Labels: enhancement
