Repository itzg/docker-minecraft-server, pull requests merged in 2024-10, with the labels that each got.

#3091 examples: updated BMC4 for v32.5
  examples/bmc4/docker-compose.yml
Labels: documentation

#3092 For FTBA support extra mods with Modrinth/CurseForge
  scripts/start-deployFTBA
Labels: enhancement

#3096 modrinth: support datapack retrieval
  Dockerfile
  docs/mods-and-plugins/modrinth.md
  scripts/start-setupModpack
Labels: enhancement

#3102 curseforge: cache get mod info and file API calls to disk
  Dockerfile
Labels: enhancement

#3103 Add SKIP_CHOWN_DATA to skip the "Changing ownership of /data"
  docs/misc/troubleshooting.md
  scripts/start
Labels: enhancement

#3107 cf: default API cache TTL to 2 days and allow config
  Dockerfile
  docs/mods-and-plugins/modrinth.md
  scripts/start-deployAutoCF
Labels: enhancement

#3110 cf: gracefully handle corrupted API cache index
  Dockerfile
Labels: bug

#3111 chore(docs): note add mod var for auto_curseforge use
  docs/types-and-platforms/mod-platforms/auto-curseforge.md
Labels: documentation

#3122 Fix incorrect warning about setting TYPE and MODPACK_PLATFORM
  scripts/start-configuration
Labels: bug
