Repository itzg/docker-minecraft-server, pull requests merged in 2024-03, with the labels that each got.

#2691 Use FTB_DIR for log4j2 patched files...hypothetically
  scripts/start-finalExec
Labels: enhancement

#2703 modrinth: add MODRINTH_OVERRIDES_EXCLUSIONS option
  Dockerfile
  docs/types-and-platforms/mod-platforms/modrinth-modpacks.md
  examples/bmc4/docker-compose.yml
  scripts/start-deployModrinth
Labels: enhancement

#2711 Remove Java 8 warning and 5 second delay
  scripts/start-configuration
  scripts/start-utils
Labels: bug

#2721 Fallback to existing server file when getbukkit retrieval fails
  examples/docker-compose.yml
  examples/spigot/docker-compose.yml
  scripts/start-deployBukkitSpigot
Labels: bug

#2723 docs: add warning that GetBukkit is dead
  docs/types-and-platforms/server-types/bukkit-spigot.md
Labels: documentation

#2726 Successful spigot/bukkit update check caused grep to fail
  docs/types-and-platforms/server-types/bukkit-spigot.md
  scripts/start-deployBukkitSpigot
Labels: bug

#2740 Hybrid servers using CURSEFORGE_FILES assume mc-mods for Forge
  examples/ketting/docker-compose.yml
  scripts/start-setupModpack
Labels: enhancement

#2747 ADD : Tailscale docker-compose yml example
  examples/docker-compose-tailscale.yml
Labels: documentation
