Repository itzg/docker-minecraft-server, pull requests merged in 2025-07, with the labels that each got.

#3527 When using a custom server, allow specifying MODRINTH_LOADER with MODRINTH_PROJECTS
  docs/mods-and-plugins/modrinth.md
  scripts/start-setupModpack
  scripts/start-utils
Labels: bug

#3531 Add back java16 variant for Paper 1.16.5 Also - remove non-JRE java8 variants to offset extra builds
  .github/workflows/build-multiarch.yml
  docs/versions/java.md
Labels: enhancement

#3535 Quieter Paper/Bukkit default configs downloading
  Dockerfile
  docs/types-and-platforms/server-types/paper.md
  scripts/start-setupEnvVariables
Labels: enhancement

#3538 Move page about building image out of contributing section
  docs/misc/building.md
Labels: documentation

#3540 Add a MOTD example with placeholders
  docs/configuration/server-properties.md
  docs/img/motd-with-placeholders.png
  examples/craftoria/docker-compose.yml
Labels: documentation

#3544 Excluding BetterGrassify and Distration Free Recipes
  files/cf-exclude-include.json
  files/modrinth-exclude-include.json
Labels: enhancement

#3549 docs: fix incorrect Minecraft version link
  docs/index.md
Labels: documentation

#3552 Docs: fix env var for enabling query
  docs/configuration/server-properties.md
Labels: documentation

#3559 fabric: add option to force reinstall
  docs/types-and-platforms/server-types/fabric.md
  scripts/start-deployFabric
Labels: enhancement

#3555 cf: exclude fastquit
  files/cf-exclude-include.json
  files/modrinth-exclude-include.json
Labels: enhancement

#3569 Upgrade dev mkdocs to Python 3.11
  docs/Dockerfile
Labels: documentation

#3570 modrinth: prioritize target loader when resolving project versions
  Dockerfile
Labels: enhancement
