Repository itzg/docker-minecraft-server, pull requests merged in 2025-05, with the labels that each got.

#3322 Use /data/tmp for WORLD zip preparation
  scripts/start-setupWorld
Labels: enhancement, status/stale

#3439 Added Ansible and MASH to deployment docs
  docs/misc/deployment/index.md
Labels: documentation

#3440 Add to global excludes the ones needed for Craftoria
  Dockerfile
  examples/craftoria/docker-compose.yml
  files/cf-exclude-include.json
Labels: enhancement

#3449 cf: fix missing comma in cf-exclude-include.json
  files/cf-exclude-include.json
Labels: bug

#3467 examples: increase memory for ftba example
  examples/ftba/compose.yml
Labels: documentation

#3474 Generalize info about UID/GID
  docs/configuration/misc-options.md
Labels: documentation
