Repository itzg/docker-minecraft-server, pull requests merged in 2025-09, with the labels that each got.

#3661 Improve local development
  Dockerfile
  docs/misc/contributing/development.md
  files/knockd-config.cfg
  files/shims/mc-health
  files/shims/mc-send-to-console
  files/shims/rcon-cmds-daemon.sh
  scripts/auto/autopause-daemon.sh
  scripts/auto/autopause-fcns.sh
  scripts/auto/autostop-daemon.sh
  scripts/auto/pause.sh
  scripts/auto/resume.sh
  scripts/auto/stop.sh
  scripts/start
  scripts/start-autopause
  scripts/start-autostop
  scripts/start-configuration
  scripts/start-deployArcLight
  scripts/start-deployAutoCF
  scripts/start-deployBukkitSpigot
  scripts/start-deployCF
  scripts/start-deployCanyon
  scripts/start-deployCatserver
  scripts/start-deployCrucible
  scripts/start-deployCustom
  scripts/start-deployFTBA
  scripts/start-deployFabric
  scripts/start-deployFolia
  scripts/start-deployForge
  scripts/start-deployKetting
  scripts/start-deployLeaf
  scripts/start-deployLimbo
  scripts/start-deployMagma
  scripts/start-deployMagmaMaintained
  scripts/start-deployModrinth
  scripts/start-deployMohist
  scripts/start-deployNanoLimbo
  scripts/start-deployNeoForge
  scripts/start-deployPaper
  scripts/start-deployPoseidon
  scripts/start-deployPufferfish
  scripts/start-deployPurpur
  scripts/start-deployQuilt
  scripts/start-deploySpongeVanilla
  scripts/start-deployVanilla
  scripts/start-finalExec
  scripts/start-rconcmds
  scripts/start-setupDatapack
  scripts/start-setupEnvVariables
  scripts/start-setupModpack
  scripts/start-setupMounts
  scripts/start-setupRbac
  scripts/start-setupServerProperties
  scripts/start-setupWorld
  scripts/start-spiget
  tests/setuponlytests/nanolimbo/require.sh
Labels: enhancement

#3662 Corrected retrieval of NanoLimbo release file
  scripts/start-deployNanoLimbo
  tests/setuponlytests/nanolimbo/require.sh
  tests/setuponlytests/nanolimbo/verify.sh
  tests/setuponlytests/test.sh
Labels: bug

#3674 Add "ok menu" and "particle rain" to default excludes
  files/cf-exclude-include.json
  files/modrinth-exclude-include.json
Labels: enhancement

#3675 Added java25 images, deprecated java24
  .github/workflows/build-multiarch.yml
  docs/versions/java.md
  images.json
Labels: enhancement

#3677 Update Greg Tech New Horizons compose file example
  examples/gtnh/docker-compose.yaml
Labels: documentation

#3678 deps: upgrade mc-server-runner 1.13.4 for CVE fixes
  Dockerfile
Labels: dependencies
