Repository itzg/docker-minecraft-server, pull requests merged in 2025-08, with the labels that each got.

#3580 Add VERSION_FROM_MODRINTH_PROJECTS
  Dockerfile
  docs/mods-and-plugins/modrinth.md
  examples/modrinth/version-from-modrinth-projects/compose.yml
  scripts/start-configuration
Labels: enhancement

#3586 Added skyfactory 4 example and excluding waila-stages
  examples/skyfactory4/compose.yml
  files/cf-exclude-include.json
  files/modrinth-exclude-include.json
Labels: documentation

#3587 Forge promotions and maven repo URLs are configurable
  Dockerfile
  docs/types-and-platforms/server-types/forge.md
Labels: enhancement

#3594 Add clarifying information for CurseForge API keys
  docs/types-and-platforms/mod-platforms/auto-curseforge.md
Labels: documentation

#3596 Limit/config concurrent downloads for CF and Modrinth
  Dockerfile
Labels: enhancement

#3602 Populate MODPACK_NAME and MODPACK_VERSION from FTB modpacks
  docs/misc/healthcheck.md
  examples/ftba/compose.yml
  scripts/start-deployFTBA
Labels: enhancement

#3604 Analyze CF_API_KEY key when auth failures
  Dockerfile
Labels: enhancement

#3605 Fixed VERSION_FROM_MODRINTH_PROJECTS when a project has a shorter list
  Dockerfile
  scripts/start-deployModrinth
Labels: bug

#3607 misc: refactored bin content into files/shims
  Dockerfile
  files/shims/mc-health
  files/shims/mc-send-to-console
  files/shims/mcstatus
  files/shims/rcon-cmds-daemon.sh
Labels: enhancement

#3609 Add Modrinth default exclusions needed for cobbleverse
  files/modrinth-exclude-include.json
Labels: enhancement

#3612 Add images.json
  .github/workflows/build-multiarch.yml
  .github/workflows/verify-pr.yml
  docs/versions/java.md
  images.json
Labels: documentation

#3613 Added all image tags to images.json
  images.json
Labels: documentation

#3619 Provide option to disable HTTP/2 use
  Dockerfile
Labels: enhancement

#3622 modrinth: fix force include handling of default-excluded project
  Dockerfile
  files/modrinth-exclude-include.json
Labels: bug
