Repository itzg/docker-minecraft-server, pull requests merged in 2025-01, with the labels that each got.

#3226 Corrected calculation of Canyon download URL
  examples/canyon/compose.yml
  scripts/start-deployCanyon
Labels: bug

#3227 neoforge: grab latest beta even when non-beta release is newer
  Dockerfile
Labels: bug

#3229 Install tput for colorized logs on alpine images
  build/alpine/install-packages.sh
Labels: bug

#3231 Added compose example snippets for Paper docs
  docs/index.md
  docs/types-and-platforms/server-types/paper.md
Labels: documentation

#3235 Added example for skyfactory5
  examples/multiline-motd/docker-compose.yml
  examples/skyfactory5/compose.yml
  files/cf-exclude-include.json
Labels: documentation

#3237 cf: gracefully handle invalid modpack manifest file
  Dockerfile
Labels: enhancement

#3238 Fixed compose error due to missing key in GTNH example
  examples/gtnh/docker-compose.yaml
Labels: documentation

#3242 modrinth: added excludes needed for create_plus
  files/modrinth-exclude-include.json
Labels: enhancement

#3244 ketting: fixed launcher invocation
  scripts/start-deployKetting
Labels: bug

#3254 cf: qualify mapping of excluded slug to mod IDs
  Dockerfile
Labels: bug

#3256 cf: handle spaces around commas for includes/excludes
  Dockerfile
Labels: enhancement

#3257 examples: adjust gtnh example to use MEMORY and JVM_OPTS
  examples/gtnh/docker-compose.yaml
Labels: documentation

#3258 Version bump GTNH to 2.7.2
  examples/gtnh/docker-compose.yaml
Labels: documentation

#3264 Clarify java edition aspect
  README.md
Labels: documentation

#3287 Clarify Vanilla Tweaks file documentation
  docs/misc/world-data.md
Labels: documentation
