Repository itzg/docker-minecraft-server, pull requests merged in 2025-04, with the labels that each got.

#3387 docs: clarify Fabric docs TYPE usage
  docs/types-and-platforms/server-types/fabric.md
Labels: documentation

#3394 fabric: retry loader version lookup
  Dockerfile
Labels: enhancement

#3398 docs: added info about image labels
  docs/misc/troubleshooting.md
Labels: documentation

#3399 docs: fix formatting for image labels list
  docs/misc/troubleshooting.md
Labels: documentation

#3400 build: add image info properties
  .github/workflows/build-multiarch.yml
  Dockerfile
  scripts/start-configuration
Labels: enhancement

#3401 docs: add a note about downloading fabric-api
  docs/types-and-platforms/server-types/fabric.md
  examples/fabric/compose.yml
Labels: documentation

#3404 add resources key to docker compose jvm options
  docs/configuration/jvm-options.md
Labels: documentation

#3411 fabric: accept shared-fetch/netty arguments
  Dockerfile
Labels: enhancement

#3412 deps: upgrade tools to Go 1.24.2
  Dockerfile
Labels: dependencies

#3420 Add Java 24 image variants
  .github/workflows/build-multiarch.yml
  docs/versions/java.md
Labels: enhancement

#3421 Corrected build entries for Java 24
  .github/workflows/build-multiarch.yml
Labels: enhancement

#3430 Revert (for now) the feature to limit concurrent modpack file downloads
  Dockerfile
  tests/setuponlytests/auto_curseforge/docker-compose.yml
  tests/setuponlytests/test.sh
Labels: bug

#3431 Change auto_curseforge test to use CF_PAGE_URL
  tests/setuponlytests/auto_curseforge/docker-compose.yml
Labels: bug
