Repository itzg/docker-minecraft-server, pull requests merged in 2025-03, with the labels that each got.

#3353 examples: moved fabric into its own directory
  examples/autopause/compose.yml
Labels: documentation

#3354 rcon-cli upgraded to support command history
  Dockerfile
Labels: enhancement

#3361 Exclude compass-coords globally from cf and mr, client side mod
  files/cf-exclude-include.json
  files/modrinth-exclude-include.json
Labels: enhancement

#3360 Lazymc - Update misc examples with non-deprecated method of managing lazymc
  docs/misc/examples.md
  examples/lazymc/docker_compose.yml
Labels: documentation

#3365 Add AUTOPAUSE_STATUS_RETRY_LIMIT and AUTOPAUSE_STATUS_RETRY_INTERVAL
  docs/misc/autopause-autostop/autopause.md
  docs/misc/autopause-autostop/autostop.md
  examples/autopause/compose.yml
  files/auto/autopause-fcns.sh
Labels: enhancement

#3371 docs: clarify that ICON can be a container path
  docs/configuration/server-properties.md
Labels: documentation

#3374 Fix SKIP_CHOWN_DATA
  scripts/start
Labels: bug

#3375 Add Docker logo to badges
  README.md
Labels: documentation

#3377 Support multiple values for COPY_PLUGINS_SRC, COPY_MODS_SRC, and COPY_CONFIG_SRC
  Dockerfile
  docs/mods-and-plugins/index.md
  examples/paper/compose.yml
  examples/paper/paper-build-plugins/Dockerfile
  examples/paper/paper-build-plugins/docker-compose.yml
  examples/paper/paper-build-plugins/plugins/.gitignore
  examples/paper/paper-build-plugins/plugins/README.md
  examples/paper/paper-proxy-protocol/config/paper-global.yml
  examples/paper/paper-proxy-protocol/docker-compose.yml
  scripts/start-setupMounts
Labels: enhancement

#3378 docs: show example of MODRINTH_PROJECTS with version number
  docs/mods-and-plugins/modrinth.md
Labels: documentation
